# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Isaac Mackle
email: isaac.mackle@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Isaac Mackle.  I’m currently in my third year at Ara in my Bachelor of IT and wish to gain further experience in my field.
  
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  ism0080
linkedin_username:	ism0080

# Build settings
markdown: kramdown