var GAME_LEVELS = [
  ["                                ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  xxxxxxxxxxxxxxxxvvxxvvvvvvxx  ",
   "  x                          x  ",
   "  x                          x  ",
   "  x   x            x         x  ",
   "  x   x                      x  ",
   "  x   x           x          x  ",
   "  x   x           x          x  ",
   "  x   xx         xxx         x  ",
   "  x   =x        xxxxx        x  ",
   "  x   xx       xxxxxxx       x  ",
   "  x @ x    xxxxxxxxxxxx      x  ",
   "  xxxxx    !!!!xxxxxxxxx     x  ",
   "  x!!!=      !!xxxxxxxxxxx xxx  ",
   "  x!!!     =!!!xx      xxx   x  ",
   "  x!!!!                      x  ",
   "  x!!!=                      x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxx    x  ",
   "  xxxxx                      x  ",
   "  xxxxx                      x  ",
   "  xxx!!   xxxxxxxxxxxxxxxxxxxx  ",
   "  xx!!                     o x  ",
   "  x!!!                       x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                "],
  ["                                ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "  x=                         x  ",
   "  x                          x  ",
   "  x                         =x  ",
   "  x     !!!!!!!xx   xx!!!!!!!x  ",
   "  x     !!!!!!!x!   !x!!!!!!!x  ",
   "  x     !!!!!!!x!   !x!!!!!!!x  ",
   "  x     !!!!!!!x!   !x!!!!!!!x  ",
   "  x     !!!!!!!x!   !x!!!!!!!x  ",
   "  x     xxxx!!!x    =x!!!!!!!x  ",
   "  x     x!o! v x!   !x!!!!!!!x  ",
   "  x     x      x!   !x!!!!!!!x  ",
   "  x     x      x!   !x!!!!!!!x  ",
   "  x     x      x!   !x!!!!!!!x  ",
   "  x     xxx    x!   !x!!!!!!!x  ",
   "  x            x!   !x!!!!!!!x  ",
   "  x            x!   !x!!!!!!!x  ",
   "  xxxxxxxxxxxxxx!   !xxxxxxxxx  ",
   "  x!       xx!               x  ",
   "  x!                         x  ",
   "  x!   x!       =           =x  ",
   "  x!   xxxxxxxxxxxxxxxxxxxxxxx  ",
   "  x!                        !x  ",
   "  x!                         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxx  x  ",
   "  x                          x  ",
   "  x@                         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                "],
  ["                                ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "  x                          x  ",
   "  x                          x  ",
   "  x                          x  ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  x!                        !x  ",
   "  x!                        !x  ",
   "  x!  !!!!!!!!!!!!!!!!!!    !x  ",
   "  x!  !               !=    !x  ",
   "  x!  !           !!!!!     !x  ",
   "  x!  !          !!!!!!!    !x  ",
   "  x!  !         !!!!!!!!!   !x  ",
   "  x!  !!!!!!!!!!!!!!!!!!!   !x  ",
   "  x!              ! o!!!!   !x  ",
   "  x!             @!  !!!!   !x  ",
   "  x!!!!!!!!!!!!!!!!  !!!!   !x  ",
   "  x             !!!  !!!!   !x  ",
   "  x              !!  !!!    !x  ",
   "  x!!!!!!!!!!!!!  !  !!=    !x  ",
   "  xv                    !   !x  ",
   "  x                     !   !x  ",
   "  x   !!!!!!!!!         !   !x  ",
   "  x   !                 !   !x  ",
   "  x   !!!!!!!!!!!!!!!!!!!   !x  ",
   "  x                         !x  ",
   "  x                         !x  ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                "],
 ];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
